export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const UPDATE_HTML_CODE = 'UPDATE_HTML_CODE';
export const UPDATE_CSS_CODE = 'UPDATE_CSS_CODE';
export const NEXT_CHAPTER = 'NEXT_CHAPTER';